<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="53" started-at="2021-10-14T14:45:15Z" finished-at="2021-10-14T14:45:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="53" started-at="2021-10-14T14:45:15Z" finished-at="2021-10-14T14:45:15Z">
      <class name="Academy.ValidateTitle">
        <test-method status="FAIL" signature="start()[pri:0, instance:Academy.ValidateTitle@4c39bec8]" name="start" is-config="true" duration-ms="0" started-at="2021-10-14T20:15:15Z" finished-at="2021-10-14T20:15:15Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at resources.Base.initializeDriver(Base.java:46)
	at Academy.ValidateTitle.start(ValidateTitle.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="SKIP" signature="validateAppTitle()[pri:0, instance:Academy.ValidateTitle@4c39bec8]" name="validateAppTitle" duration-ms="3" started-at="2021-10-14T20:15:15Z" finished-at="2021-10-14T20:15:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAppTitle -->
        <test-method status="SKIP" signature="validateHeader()[pri:0, instance:Academy.ValidateTitle@4c39bec8]" name="validateHeader" duration-ms="2" started-at="2021-10-14T20:15:15Z" finished-at="2021-10-14T20:15:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeader -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:Academy.ValidateTitle@4c39bec8]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-10-14T20:15:15Z" finished-at="2021-10-14T20:15:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Academy.ValidateTitle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
